#!/bin/bash
# test_live_migration.sh - KVM热迁移测试

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RESULTS_DIR="$SCRIPT_DIR/../results/migration-$(date +%Y%m%d-%H%M%S)"
VM_NAME="migration-test-vm"
IMAGE_DIR="$SCRIPT_DIR/../images"
TEST_IMAGE="$IMAGE_DIR/migration-test.qcow2"

echo "========================================"
echo "KVM热迁移测试"
echo "========================================"
echo ""

# 检查权限
if [[ $EUID -ne 0 ]]; then
   echo "错误: 此脚本需要 root 权限"
   echo "使用: sudo $0"
   exit 1
fi

mkdir -p "$RESULTS_DIR"
mkdir -p "$IMAGE_DIR"

# 检查依赖
echo "步骤 1: 检查环境依赖..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

DEPS_OK=1

# 检查QEMU
if command -v qemu-system-x86_64 &> /dev/null; then
    echo "✓ QEMU已安装: $(qemu-system-x86_64 --version | head -1)"
else
    echo "✗ QEMU未安装"
    DEPS_OK=0
fi

# 检查libvirt
if command -v virsh &> /dev/null; then
    echo "✓ libvirt已安装: $(virsh version --short 2>/dev/null || echo '未知版本')"
    LIBVIRT_AVAILABLE=1
else
    echo "⚠ libvirt未安装（可选，但推荐用于热迁移）"
    LIBVIRT_AVAILABLE=0
fi

# 检查KVM
if [[ ! -e /dev/kvm ]]; then
    echo "✗ /dev/kvm不存在，KVM未启用"
    DEPS_OK=0
else
    echo "✓ /dev/kvm存在"
fi

# 检查网络工具
if command -v nc &> /dev/null || command -v netcat &> /dev/null; then
    echo "✓ netcat已安装"
else
    echo "⚠ netcat未安装（用于TCP迁移测试）"
fi

echo ""

if [[ $DEPS_OK -eq 0 ]]; then
    echo "✗ 缺少必要依赖，请先安装QEMU和KVM"
    exit 1
fi

# 热迁移原理说明
echo "步骤 2: 热迁移原理..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

{
    echo "KVM热迁移原理"
    echo "========================================"
    echo ""
    echo "热迁移类型:"
    echo "  1. 离线迁移 (Offline Migration)"
    echo "     - 关闭VM后迁移"
    echo "     - 停机时间长"
    echo "     - 最简单可靠"
    echo ""
    echo "  2. 在线迁移 (Live Migration)"
    echo "     - VM运行状态下迁移"
    echo "     - 停机时间短（毫秒级）"
    echo "     - 需要共享存储或存储迁移"
    echo ""
    echo "  3. 存储迁移 (Storage Migration)"
    echo "     - 同时迁移VM和磁盘"
    echo "     - 不需要共享存储"
    echo "     - 时间较长"
    echo ""
    echo "热迁移过程:"
    echo "  阶段1: 预迁移 (Pre-migration)"
    echo "    - 在目标主机启动VM实例"
    echo "    - 建立迁移连接"
    echo ""
    echo "  阶段2: 迭代拷贝 (Iterative Copy)"
    echo "    - 复制内存页到目标主机"
    echo "    - 标记脏页（dirty pages）"
    echo "    - 多轮迭代直到脏页率降低"
    echo ""
    echo "  阶段3: 停止并拷贝 (Stop-and-Copy)"
    echo "    - 暂停源VM"
    echo "    - 传输剩余脏页和CPU状态"
    echo "    - 停机时间窗口"
    echo ""
    echo "  阶段4: 提交 (Commit)"
    echo "    - 在目标主机激活VM"
    echo "    - 销毁源VM"
    echo "    - 完成迁移"
    echo ""
    echo "关键技术:"
    echo "  - Pre-copy: 先复制内存，边运行边迭代"
    echo "  - Post-copy: 先启动目标VM，按需传输内存"
    echo "  - RDMA: 使用RDMA加速内存传输"
    echo "  - 压缩: 压缩内存页减少传输量"
    echo "  - 多线程: 并行传输提高速度"
    echo ""
} | tee "$RESULTS_DIR/principles.txt"

# 检查热迁移要求
echo "步骤 3: 检查热迁移要求..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

{
    echo "热迁移要求检查"
    echo "========================================"
    echo ""

    echo "硬件要求:"
    # 检查CPU兼容性
    CPU_MODEL=$(grep "model name" /proc/cpuinfo | head -1 | cut -d: -f2 | xargs)
    echo "  CPU型号: $CPU_MODEL"

    # 检查虚拟化支持
    if grep -q "vmx\|svm" /proc/cpuinfo; then
        echo "  ✓ CPU支持虚拟化"
    else
        echo "  ✗ CPU不支持虚拟化"
    fi

    echo ""
    echo "网络要求:"
    # 检查网络接口
    echo "  可用网络接口:"
    ip -br addr show | grep -v "^lo" | while read iface state addr; do
        echo "    - $iface: $state ($addr)"
    done

    echo ""
    echo "存储要求:"
    echo "  共享存储方式:"
    echo "    - NFS共享存储"
    echo "    - iSCSI存储"
    echo "    - Ceph/GlusterFS分布式存储"
    echo "  或使用存储迁移（--copy-storage-all）"

    echo ""
    echo "软件要求:"
    echo "  源主机和目标主机需要:"
    echo "    - 相同或兼容的QEMU版本"
    echo "    - 相同的libvirt版本"
    echo "    - 相同的CPU型号（或使用CPU兼容模式）"
    echo "    - 网络连通性"

} | tee "$RESULTS_DIR/requirements.txt"

echo ""

# 创建测试虚拟机镜像
echo "步骤 4: 准备测试虚拟机..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

if [[ ! -f "$TEST_IMAGE" ]]; then
    echo "创建测试镜像（2GB）..."
    qemu-img create -f qcow2 "$TEST_IMAGE" 2G

    if [[ $? -eq 0 ]]; then
        echo "✓ 测试镜像创建成功"
    else
        echo "✗ 测试镜像创建失败"
        exit 1
    fi
else
    echo "✓ 测试镜像已存在: $TEST_IMAGE"
fi

echo ""
echo "镜像信息:"
qemu-img info "$TEST_IMAGE" | tee "$RESULTS_DIR/image-info.txt"

echo ""

# QEMU热迁移测试（单机模拟）
echo "步骤 5: QEMU热迁移测试（单机模拟）..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

echo "说明: 在单机上模拟热迁移过程"
echo ""

{
    echo "QEMU热迁移命令示例"
    echo "========================================"
    echo ""
    echo "源主机启动VM（监听迁移端口）:"
    echo "qemu-system-x86_64 \\"
    echo "    -enable-kvm \\"
    echo "    -m 512 \\"
    echo "    -smp 2 \\"
    echo "    -drive file=$TEST_IMAGE,format=qcow2 \\"
    echo "    -monitor stdio \\"
    echo "    -nographic"
    echo ""
    echo "QEMU Monitor命令开始迁移:"
    echo "  migrate -d tcp:localhost:4444"
    echo ""
    echo "目标主机（接收迁移）:"
    echo "qemu-system-x86_64 \\"
    echo "    -enable-kvm \\"
    echo "    -m 512 \\"
    echo "    -smp 2 \\"
    echo "    -drive file=$TEST_IMAGE,format=qcow2 \\"
    echo "    -incoming tcp:0.0.0.0:4444 \\"
    echo "    -monitor stdio \\"
    echo "    -nographic"
    echo ""
    echo "监控迁移状态:"
    echo "  (qemu) info migrate"
    echo ""
    echo "取消迁移:"
    echo "  (qemu) migrate_cancel"
    echo ""
} | tee "$RESULTS_DIR/qemu-migration.txt"

# libvirt热迁移测试
if [[ $LIBVIRT_AVAILABLE -eq 1 ]]; then
    echo "步骤 6: libvirt热迁移配置..."
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    {
        echo "libvirt热迁移配置"
        echo "========================================"
        echo ""
        echo "1. 本地测试（同主机不同libvirt URI）:"
        echo "   virsh migrate $VM_NAME qemu:///system qemu:///session"
        echo ""
        echo "2. TCP迁移（无加密）:"
        echo "   # 目标主机配置 /etc/libvirt/libvirtd.conf"
        echo "   listen_tls = 0"
        echo "   listen_tcp = 1"
        echo "   tcp_port = \"16509\""
        echo "   auth_tcp = \"none\""
        echo ""
        echo "   # 重启libvirtd"
        echo "   systemctl restart libvirtd"
        echo ""
        echo "   # 执行迁移"
        echo "   virsh migrate --live $VM_NAME \\"
        echo "       qemu+tcp://target-host/system"
        echo ""
        echo "3. SSH迁移（推荐，安全）:"
        echo "   # 确保SSH密钥认证配置完成"
        echo "   virsh migrate --live $VM_NAME \\"
        echo "       qemu+ssh://target-host/system"
        echo ""
        echo "4. TLS加密迁移:"
        echo "   # 配置TLS证书后"
        echo "   virsh migrate --live $VM_NAME \\"
        echo "       qemu+tls://target-host/system"
        echo ""
        echo "5. 带存储迁移:"
        echo "   virsh migrate --live --copy-storage-all $VM_NAME \\"
        echo "       qemu+ssh://target-host/system"
        echo ""
        echo "6. 离线迁移:"
        echo "   virsh migrate --offline $VM_NAME \\"
        echo "       qemu+ssh://target-host/system"
        echo ""
        echo "迁移选项:"
        echo "  --live              # 在线迁移"
        echo "  --offline           # 离线迁移"
        echo "  --p2p               # 点对点迁移"
        echo "  --direct            # 直接迁移"
        echo "  --tunnelled         # 隧道迁移（通过libvirtd）"
        echo "  --persistent        # 保持VM定义"
        echo "  --undefinesource    # 删除源VM定义"
        echo "  --suspend           # 迁移后暂停"
        echo "  --copy-storage-all  # 复制所有存储"
        echo "  --copy-storage-inc  # 增量存储复制"
        echo "  --verbose           # 显示详细进度"
        echo "  --timeout N         # 超时时间（秒）"
        echo ""
        echo "监控迁移进度:"
        echo "  virsh domjobinfo $VM_NAME --completed"
        echo ""
        echo "取消迁移:"
        echo "  virsh domjobabort $VM_NAME"
        echo ""
    } | tee "$RESULTS_DIR/libvirt-migration.txt"

    echo ""

    # 检查libvirt迁移配置
    echo "步骤 7: 检查libvirt配置..."
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo ""

    {
        echo "libvirt配置检查"
        echo "========================================"
        echo ""

        echo "libvirtd状态:"
        systemctl is-active libvirtd &>/dev/null && echo "  ✓ libvirtd运行中" || echo "  ✗ libvirtd未运行"

        echo ""
        echo "网络配置:"
        virsh net-list --all 2>/dev/null || echo "  无法列出网络"

        echo ""
        echo "当前虚拟机:"
        virsh list --all 2>/dev/null || echo "  无法列出虚拟机"

        echo ""
        echo "连接URI:"
        echo "  默认: qemu:///system"
        virsh uri 2>/dev/null

    } | tee "$RESULTS_DIR/libvirt-config.txt"

    echo ""
fi

# 性能优化
echo "步骤 8: 热迁移性能优化..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

{
    echo "热迁移性能优化"
    echo "========================================"
    echo ""
    echo "1. 内存优化:"
    echo "   # 启用压缩"
    echo "   virsh migrate --live --compressed $VM_NAME target"
    echo ""
    echo "   # 设置迁移带宽（MB/s）"
    echo "   virsh migrate-setspeed $VM_NAME 1000"
    echo ""
    echo "   # 设置最大停机时间（毫秒）"
    echo "   virsh migrate-setmaxdowntime $VM_NAME 500"
    echo ""
    echo "   # QEMU monitor设置"
    echo "   (qemu) migrate_set_speed 1000M"
    echo "   (qemu) migrate_set_downtime 0.5"
    echo ""
    echo "2. 网络优化:"
    echo "   # 使用高速网络（10GbE或更高）"
    echo "   # 使用RDMA（如果硬件支持）"
    echo "   virsh migrate --live --rdma-pin-all $VM_NAME target"
    echo ""
    echo "   # 调整TCP参数"
    echo "   sysctl -w net.core.rmem_max=134217728"
    echo "   sysctl -w net.core.wmem_max=134217728"
    echo "   sysctl -w net.ipv4.tcp_rmem='4096 87380 67108864'"
    echo "   sysctl -w net.ipv4.tcp_wmem='4096 65536 67108864'"
    echo ""
    echo "3. CPU兼容性:"
    echo "   # 使用CPU兼容模式"
    echo "   <cpu mode='custom' match='exact'>"
    echo "     <model>qemu64</model>"
    echo "   </cpu>"
    echo ""
    echo "   # 或使用host-passthrough（需要相同CPU）"
    echo "   <cpu mode='host-passthrough'/>"
    echo ""
    echo "4. 存储优化:"
    echo "   # 使用qcow2格式"
    echo "   # 启用缓存"
    echo "   <driver name='qemu' type='qcow2' cache='none'/>"
    echo ""
    echo "   # 使用NFS v4"
    echo "   mount -t nfs -o vers=4,hard,intr server:/share /mnt"
    echo ""
    echo "5. 迁移策略:"
    echo "   # Post-copy模式（适合内存密集型）"
    echo "   virsh migrate --live --postcopy $VM_NAME target"
    echo ""
    echo "   # Auto-converge（自动调整vCPU降低脏页率）"
    echo "   virsh migrate --live --auto-converge $VM_NAME target"
    echo ""
    echo "   # 并行迁移"
    echo "   virsh migrate --live --parallel --parallel-connections 4 $VM_NAME target"
    echo ""
} | tee "$RESULTS_DIR/optimization.txt"

echo ""

# 故障排查
echo "步骤 9: 故障排查..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

{
    echo "热迁移故障排查"
    echo "========================================"
    echo ""
    echo "问题1: 迁移失败 - CPU不兼容"
    echo "现象: error: internal error: unable to execute QEMU command 'migrate'"
    echo "原因: 源和目标CPU型号不同"
    echo "解决:"
    echo "  1. 使用CPU兼容模式"
    echo "     virsh edit $VM_NAME"
    echo "     <cpu mode='custom' match='exact'>"
    echo "       <model>qemu64</model>"
    echo "     </cpu>"
    echo ""
    echo "  2. 或使用最小CPU特性集"
    echo "     -cpu Nehalem  # 在QEMU命令行"
    echo ""
    echo "问题2: 迁移超时"
    echo "现象: 迁移长时间不完成"
    echo "原因: 脏页产生速度>传输速度"
    echo "解决:"
    echo "  1. 增加迁移带宽"
    echo "     virsh migrate-setspeed $VM_NAME 2000"
    echo ""
    echo "  2. 使用auto-converge"
    echo "     virsh migrate --live --auto-converge $VM_NAME target"
    echo ""
    echo "  3. 使用post-copy"
    echo "     virsh migrate --live --postcopy $VM_NAME target"
    echo ""
    echo "问题3: 网络连接失败"
    echo "现象: Unable to connect to server"
    echo "原因: 防火墙/网络不通"
    echo "解决:"
    echo "  1. 检查防火墙"
    echo "     firewall-cmd --add-port=16509/tcp --permanent"
    echo "     firewall-cmd --reload"
    echo ""
    echo "  2. 测试连通性"
    echo "     nc -zv target-host 16509"
    echo ""
    echo "  3. 使用SSH迁移"
    echo "     virsh migrate --live qemu+ssh://target/system"
    echo ""
    echo "问题4: 存储访问失败"
    echo "现象: error: Cannot access storage file"
    echo "原因: 目标主机无法访问镜像"
    echo "解决:"
    echo "  1. 使用共享存储（NFS/iSCSI）"
    echo "  2. 使用存储迁移"
    echo "     virsh migrate --live --copy-storage-all $VM_NAME target"
    echo ""
    echo "问题5: 权限错误"
    echo "现象: Permission denied"
    echo "原因: SELinux/AppArmor限制"
    echo "解决:"
    echo "  # 临时禁用SELinux（测试用）"
    echo "  setenforce 0"
    echo ""
    echo "  # 或配置SELinux"
    echo "  setsebool -P virt_use_nfs 1"
    echo ""
    echo "调试命令:"
    echo "  # 查看迁移日志"
    echo "  journalctl -u libvirtd -f"
    echo ""
    echo "  # 查看QEMU日志"
    echo "  tail -f /var/log/libvirt/qemu/$VM_NAME.log"
    echo ""
    echo "  # 详细迁移信息"
    echo "  virsh migrate --live --verbose --debug $VM_NAME target"
    echo ""
} | tee "$RESULTS_DIR/troubleshooting.txt"

echo ""

# 实际迁移测试示例
echo "步骤 10: 迁移测试示例..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

{
    echo "完整迁移测试示例"
    echo "========================================"
    echo ""
    echo "场景1: 单机QEMU迁移测试"
    echo "----------------------------------------"
    echo ""
    echo "终端1 - 启动源VM:"
    echo "qemu-system-x86_64 \\"
    echo "    -enable-kvm \\"
    echo "    -m 512 \\"
    echo "    -smp 2 \\"
    echo "    -drive file=$TEST_IMAGE,format=qcow2 \\"
    echo "    -monitor telnet:127.0.0.1:4445,server,nowait \\"
    echo "    -vnc :0 \\"
    echo "    -name source-vm"
    echo ""
    echo "终端2 - 启动目标VM（等待迁移）:"
    echo "qemu-system-x86_64 \\"
    echo "    -enable-kvm \\"
    echo "    -m 512 \\"
    echo "    -smp 2 \\"
    echo "    -drive file=$TEST_IMAGE,format=qcow2 \\"
    echo "    -incoming tcp:0.0.0.0:4444 \\"
    echo "    -monitor telnet:127.0.0.1:4446,server,nowait \\"
    echo "    -vnc :1 \\"
    echo "    -name dest-vm"
    echo ""
    echo "终端3 - 执行迁移:"
    echo "telnet localhost 4445"
    echo "(qemu) migrate -d tcp:localhost:4444"
    echo "(qemu) info migrate"
    echo ""
    echo "场景2: libvirt本地迁移测试"
    echo "----------------------------------------"
    echo ""
    echo "# 创建测试VM"
    echo "virt-install \\"
    echo "    --name test-migrate \\"
    echo "    --ram 512 \\"
    echo "    --disk path=$TEST_IMAGE,format=qcow2 \\"
    echo "    --vcpus 1 \\"
    echo "    --os-variant generic \\"
    echo "    --network network=default \\"
    echo "    --graphics none \\"
    echo "    --noautoconsole \\"
    echo "    --import"
    echo ""
    echo "# 启动VM"
    echo "virsh start test-migrate"
    echo ""
    echo "# 模拟迁移（需要配置第二个libvirt连接）"
    echo "virsh migrate --live test-migrate qemu:///system"
    echo ""
    echo "场景3: 双主机SSH迁移"
    echo "----------------------------------------"
    echo ""
    echo "准备工作:"
    echo "  1. 配置SSH密钥认证"
    echo "     ssh-keygen"
    echo "     ssh-copy-id root@target-host"
    echo ""
    echo "  2. 确保共享存储或使用存储迁移"
    echo ""
    echo "执行迁移:"
    echo "  virsh migrate --live \\"
    echo "      --verbose \\"
    echo "      test-migrate \\"
    echo "      qemu+ssh://target-host/system"
    echo ""
    echo "监控进度:"
    echo "  watch -n 1 'virsh domjobinfo test-migrate'"
    echo ""
} | tee "$RESULTS_DIR/test-examples.txt"

echo ""

# 性能基准测试
echo "步骤 11: 性能基准..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

{
    echo "热迁移性能基准"
    echo "========================================"
    echo ""
    echo "性能指标:"
    echo "  1. 总迁移时间 (Total Migration Time)"
    echo "     - 从开始到VM在目标主机完全运行的时间"
    echo ""
    echo "  2. 停机时间 (Downtime)"
    echo "     - VM在源主机停止到目标主机启动的时间"
    echo "     - 典型值: 100-500ms"
    echo "     - 目标: <100ms"
    echo ""
    echo "  3. 传输速度 (Transfer Rate)"
    echo "     - 内存传输速度（MB/s）"
    echo "     - 受网络带宽限制"
    echo ""
    echo "  4. 脏页率 (Dirty Page Rate)"
    echo "     - 内存页修改速度"
    echo "     - 影响收敛时间"
    echo ""
    echo "测试数据（参考值）:"
    echo "  配置: 4GB RAM, 1Gbps网络"
    echo "  ├─ 总时间: 30-60秒"
    echo "  ├─ 停机时间: 200-500ms"
    echo "  ├─ 传输速度: 80-100MB/s"
    echo "  └─ 迭代轮次: 3-5轮"
    echo ""
    echo "  配置: 4GB RAM, 10Gbps网络"
    echo "  ├─ 总时间: 5-10秒"
    echo "  ├─ 停机时间: 100-200ms"
    echo "  ├─ 传输速度: 500-800MB/s"
    echo "  └─ 迭代轮次: 2-3轮"
    echo ""
    echo "影响因素:"
    echo "  - VM内存大小"
    echo "  - 工作负载类型（内存密集型更慢）"
    echo "  - 网络带宽和延迟"
    echo "  - CPU性能（压缩场景）"
    echo "  - 是否使用压缩/RDMA"
    echo ""
} | tee "$RESULTS_DIR/benchmarks.txt"

echo ""

# 安全考虑
echo "步骤 12: 安全考虑..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

{
    echo "热迁移安全"
    echo "========================================"
    echo ""
    echo "安全风险:"
    echo "  1. 明文传输"
    echo "     - TCP迁移未加密"
    echo "     - 内存数据可被窃听"
    echo ""
    echo "  2. 未授权迁移"
    echo "     - 无认证的libvirtd"
    echo "     - 可能被劫持VM"
    echo ""
    echo "  3. 中间人攻击"
    echo "     - 迁移流量被劫持"
    echo "     - VM可能被替换"
    echo ""
    echo "安全措施:"
    echo "  1. 使用TLS加密"
    echo "     # 配置TLS证书"
    echo "     # /etc/libvirt/libvirtd.conf"
    echo "     listen_tls = 1"
    echo "     key_file = \"/etc/pki/libvirt/private/serverkey.pem\""
    echo "     cert_file = \"/etc/pki/libvirt/servercert.pem\""
    echo "     ca_file = \"/etc/pki/CA/cacert.pem\""
    echo ""
    echo "  2. 使用SSH隧道"
    echo "     virsh migrate --live qemu+ssh://target/system"
    echo ""
    echo "  3. 启用SASL认证"
    echo "     # /etc/libvirt/libvirtd.conf"
    echo "     auth_tcp = \"sasl\""
    echo ""
    echo "  4. 防火墙配置"
    echo "     # 仅允许特定主机"
    echo "     firewall-cmd --add-rich-rule='rule family=\"ipv4\" \\"
    echo "         source address=\"192.168.1.0/24\" \\"
    echo "         port port=\"16509\" protocol=\"tcp\" accept'"
    echo ""
    echo "  5. 审计日志"
    echo "     # 启用libvirt审计"
    echo "     audit_level = 1"
    echo "     audit_logging = 1"
    echo ""
} | tee "$RESULTS_DIR/security.txt"

echo ""

# 生成报告
{
    echo "KVM热迁移测试报告"
    echo "========================================"
    echo ""
    echo "测试时间: $(date)"
    echo ""
    echo "系统信息:"
    echo "  内核版本: $(uname -r)"
    echo "  CPU: $(grep "model name" /proc/cpuinfo | head -1 | cut -d: -f2 | xargs)"
    echo "  QEMU版本: $(qemu-system-x86_64 --version | head -1)"
    if [[ $LIBVIRT_AVAILABLE -eq 1 ]]; then
        echo "  libvirt版本: $(virsh version --short 2>/dev/null || echo '未知')"
    fi
    echo ""
    echo "测试组件:"
    echo "  ✓ 热迁移原理说明"
    echo "  ✓ 环境要求检查"
    echo "  ✓ QEMU迁移配置"
    if [[ $LIBVIRT_AVAILABLE -eq 1 ]]; then
        echo "  ✓ libvirt迁移配置"
    fi
    echo "  ✓ 性能优化建议"
    echo "  ✓ 故障排查指南"
    echo "  ✓ 测试示例"
    echo "  ✓ 性能基准"
    echo "  ✓ 安全考虑"
    echo ""
    echo "迁移类型:"
    echo "  - 在线迁移（Live Migration）"
    echo "  - 离线迁移（Offline Migration）"
    echo "  - 存储迁移（Storage Migration）"
    echo ""
    echo "传输方式:"
    echo "  - TCP（无加密）"
    echo "  - SSH（推荐）"
    echo "  - TLS（安全）"
    echo "  - RDMA（高性能）"
    echo ""
    echo "详细日志:"
    echo "  原理说明: $RESULTS_DIR/principles.txt"
    echo "  环境要求: $RESULTS_DIR/requirements.txt"
    echo "  镜像信息: $RESULTS_DIR/image-info.txt"
    echo "  QEMU迁移: $RESULTS_DIR/qemu-migration.txt"
    if [[ $LIBVIRT_AVAILABLE -eq 1 ]]; then
        echo "  libvirt迁移: $RESULTS_DIR/libvirt-migration.txt"
        echo "  libvirt配置: $RESULTS_DIR/libvirt-config.txt"
    fi
    echo "  性能优化: $RESULTS_DIR/optimization.txt"
    echo "  故障排查: $RESULTS_DIR/troubleshooting.txt"
    echo "  测试示例: $RESULTS_DIR/test-examples.txt"
    echo "  性能基准: $RESULTS_DIR/benchmarks.txt"
    echo "  安全考虑: $RESULTS_DIR/security.txt"
    echo ""
    echo "注意事项:"
    echo "  - 本测试仅生成配置和文档"
    echo "  - 实际迁移需要两台主机或配置多个libvirt连接"
    echo "  - 推荐在测试环境中先验证迁移流程"
    echo "  - 生产环境使用SSH或TLS加密迁移"
    echo ""
} | tee "$RESULTS_DIR/summary.txt"

echo "========================================"
echo "测试完成"
echo "========================================"
echo ""
echo "✓ 热迁移测试配置生成完成"
echo ""
echo "下一步:"
echo "  1. 查看详细文档: $RESULTS_DIR/"
echo "  2. 根据环境选择迁移方式（QEMU或libvirt）"
echo "  3. 配置网络和存储"
echo "  4. 在测试环境验证迁移流程"
echo ""
echo "结果目录: $RESULTS_DIR"
echo ""
