#!/bin/bash
# BCC 工具示例脚本 - 所有 10 个工具的快速示例

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║         BCC 工具使用示例                                  ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""

if [ "$EUID" -ne 0 ]; then
    echo "警告: BCC 工具需要 root 权限"
    echo "请使用: sudo $0"
    echo ""
fi

echo "========================================="
echo "1. execsnoop - 跟踪进程执行"
echo "========================================="
echo ""
echo "示例命令:"
echo "  sudo execsnoop                    # 实时显示所有新进程"
echo "  sudo execsnoop -t                 # 带时间戳"
echo "  sudo execsnoop -x                 # 只显示失败的执行"
echo "  sudo execsnoop -n bash            # 过滤进程名"
echo ""
echo "使用场景:"
echo "  - 调试启动脚本"
echo "  - 安全审计（检测可疑进程）"
echo "  - 发现短暂进程"
echo ""

echo "========================================="
echo "2. opensnoop - 跟踪文件打开"
echo "========================================="
echo ""
echo "示例命令:"
echo "  sudo opensnoop                    # 跟踪所有文件打开"
echo "  sudo opensnoop -p 1234            # 跟踪特定进程"
echo "  sudo opensnoop -n nginx           # 跟踪特定程序"
echo "  sudo opensnoop -x                 # 只显示失败的打开"
echo "  sudo opensnoop -t                 # 带时间戳"
echo ""
echo "使用场景:"
echo "  - 排查文件找不到问题"
echo "  - 分析程序依赖"
echo "  - 监控敏感文件访问"
echo ""

echo "========================================="
echo "3. biosnoop - 跟踪块I/O"
echo "========================================="
echo ""
echo "示例命令:"
echo "  sudo biosnoop                     # 跟踪所有块 I/O"
echo "  sudo biosnoop -d sda              # 跟踪特定磁盘"
echo "  sudo biosnoop -Q                  # 显示队列时间"
echo ""
echo "使用场景:"
echo "  - 磁盘性能分析"
echo "  - 识别慢 I/O 操作"
echo "  - I/O 热点分析"
echo ""

echo "========================================="
echo "4. tcpconnect - 跟踪TCP连接"
echo "========================================="
echo ""
echo "示例命令:"
echo "  sudo tcpconnect                   # 跟踪所有 TCP 连接"
echo "  sudo tcpconnect -t                # 带时间戳"
echo "  sudo tcpconnect -p 1234           # 跟踪特定进程"
echo "  sudo tcpconnect -P 80,443         # 过滤端口"
echo ""
echo "使用场景:"
echo "  - 网络连接审计"
echo "  - 服务依赖分析"
echo "  - 安全监控"
echo ""

echo "========================================="
echo "5. tcpaccept - 跟踪TCP接受"
echo "========================================="
echo ""
echo "示例命令:"
echo "  sudo tcpaccept                    # 跟踪所有 TCP 接受"
echo "  sudo tcpaccept -t                 # 带时间戳"
echo "  sudo tcpaccept -L 80              # 过滤本地端口"
echo "  sudo tcpaccept -P 1024-65535      # 过滤远程端口范围"
echo ""
echo "使用场景:"
echo "  - 服务监控（谁在连接）"
echo "  - 访问审计"
echo "  - DDoS 检测"
echo ""

echo "========================================="
echo "6. tcpretrans - 跟踪TCP重传"
echo "========================================="
echo ""
echo "示例命令:"
echo "  sudo tcpretrans                   # 跟踪所有 TCP 重传"
echo "  sudo tcpretrans -l                # 显示详细信息"
echo "  sudo tcpretrans -c                # 持续统计"
echo ""
echo "使用场景:"
echo "  - 网络质量诊断"
echo "  - 检测丢包"
echo "  - 性能问题排查"
echo ""

echo "========================================="
echo "7. runqlat - 调度队列延迟"
echo "========================================="
echo ""
echo "示例命令:"
echo "  sudo runqlat 5                    # 运行 5 秒"
echo "  sudo runqlat -m 5                 # 以毫秒为单位"
echo "  sudo runqlat -p 1234 5            # 跟踪特定进程"
echo "  sudo runqlat -i 1                 # 每秒输出一次"
echo ""
echo "使用场景:"
echo "  - CPU 饱和度分析"
echo "  - 调度性能评估"
echo "  - 实时性分析"
echo ""

echo "========================================="
echo "8. profile - CPU采样分析"
echo "========================================="
echo ""
echo "示例命令:"
echo "  sudo profile 10                   # 采样 10 秒"
echo "  sudo profile -F 99 -a 10          # 99Hz 采样所有 CPU"
echo "  sudo profile -U 10                # 只采样用户态"
echo "  sudo profile -K 10                # 只采样内核态"
echo "  sudo profile -p 1234 10           # 采样特定进程"
echo ""
echo "使用场景:"
echo "  - 性能优化（找出 CPU 热点）"
echo "  - 瓶颈分析"
echo "  - 代码 profiling"
echo ""

echo "========================================="
echo "9. offcputime - 离CPU时间分析"
echo "========================================="
echo ""
echo "示例命令:"
echo "  sudo offcputime 10                # 分析 10 秒"
echo "  sudo offcputime -p 1234 10        # 分析特定进程"
echo "  sudo offcputime -u 10             # 用户态堆栈"
echo "  sudo offcputime -k 10             # 内核态堆栈"
echo "  sudo offcputime -f 10 > out.txt   # 生成火焰图数据"
echo ""
echo "使用场景:"
echo "  - 阻塞分析（在哪里等待）"
echo "  - 锁竞争检测"
echo "  - I/O 等待分析"
echo ""

echo "========================================="
echo "10. memleak - 内存泄漏检测"
echo "========================================="
echo ""
echo "示例命令:"
echo "  sudo memleak -p 1234              # 检测进程内存泄漏"
echo "  sudo memleak -p 1234 -a 5         # 每 5 秒报告一次"
echo "  sudo memleak -k 5                 # 检测内核内存泄漏"
echo "  sudo memleak -p 1234 -t 10        # 显示调用栈，运行 10 秒"
echo ""
echo "使用场景:"
echo "  - 内存泄漏检测"
echo "  - 资源管理验证"
echo "  - 长期运行分析"
echo ""

echo "========================================="
echo "实用技巧"
echo "========================================="
echo ""

echo "1. 组合使用多个工具"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  # 在不同终端同时运行"
echo "  Terminal 1: sudo execsnoop"
echo "  Terminal 2: sudo opensnoop"
echo "  Terminal 3: sudo tcpconnect"
echo ""

echo "2. 保存输出供后续分析"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  sudo execsnoop > exec.log &"
echo "  # 运行一段时间后"
echo "  fg  # 停止"
echo "  less exec.log"
echo ""

echo "3. 过滤和分析"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  sudo execsnoop | grep python"
echo "  sudo tcpconnect | grep :80"
echo "  sudo opensnoop | awk '{print \$NF}' | sort | uniq -c | sort -rn"
echo ""

echo "4. 定时运行"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  timeout 60 sudo biosnoop > bio_1min.log"
echo "  watch -n 10 'sudo runqlat 5'"
echo ""

echo "5. 生成报告"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  sudo profile -F 99 -a 30 > profile.txt"
echo "  sudo offcputime -f 30 > offcpu.folded"
echo "  # 然后使用 flamegraph.pl 生成火焰图"
echo ""

echo "========================================="
echo "完成！"
echo "========================================="
echo ""
echo "更多信息:"
echo "  - 测试脚本: tests/bcc/"
echo "  - 详细文档: tests/bcc/README.md"
echo "  - BCC 官方: https://github.com/iovisor/bcc"
echo ""
